### ISSUE TITLE
Wrong classranges optimization

### ISSUE THREAD

**Issue by silentroach** [DmitrySoshnikov/regexp-tree#156]
Something is wrong with classranges optimizations, example here:

    $ bin/regexp-tree -e '/[^a-zA-Z0-9_!#$%&*@＠]/' -o
   
    Optimized: /[^\d!#$%&*@-Z_a-z＠]

With `charClassClassrangesMerge` optimization disabled I have better result:

    Expected:  /[^\w!#$%&*@＠]/

**Comment by DmitrySoshnikov** [comment]
@silentroach, thanks, good catch!

CC @Golmote: seems something weird is happening in the ranges, or in the recent new/old result comparison.

**Comment by silentroach** [comment]
Holy shit, it is not a bug O.o

**Comment by davisjam** [comment]
Not technically a bug, but looks like one.

I think it would be helpful to clarify the behavior of the optimizer in two places:

1. [Here](https://github.com/DmitrySoshnikov/regexp-tree#using-optimizer-api) in the main README, say "This can result in potentially-surprising results. See the README".
2. In the [optimizer README](https://github.com/DmitrySoshnikov/regexp-tree/tree/master/src/optimizer), include this kind of "optimize ranges" behavior. This does not appear to be documented at the moment.

**Comment by DmitrySoshnikov** [comment]
@davisjam, yeah, whatever that can clarify some weird behavior, and make usage easier, we can add to the README sections.

The "potentially-surprising results" wording seems a bit negative, underlying some potentially "bad parts" of the tool, which I don't like 😄I.e. instead of negative wording, we should focus on "clarifying specific features wording".

So yes, please feel free to open a PR with needed clarifications, this is always appreciated.

**Comment by davisjam** [comment]
@DmitrySoshnikov See #158.
