### ISSUE TITLE
Replace `expression`, and `expressions` with generic `body` property

### ISSUE THREAD

**Issue by DmitrySoshnikov** [DmitrySoshnikov/regexp-tree#41]
Nodes like `Group`, or `CharacterClass` have a property `expression`, or `expressions` (depending on whether it's a single node, or a collection). To simplify this, we can use a generic property called `body`, similar to how `RegExp` node type has it.

(per discussion in https://github.com/DmitrySoshnikov/regexp-tree/issues/37#issuecomment-292012662, CC @hg42)

**Comment by hg42** [comment]
it's a balancing thing...

when traversing, you have
```
# expressions vs. expression
if node.expressions
  # work on expressions array
else
  # work on expression object
```
vs. (if I understand your intent with the body member correctly):
```
# body=[...] vs. body=obj
if typeof node.body == "Array"
  # work on body as array
else
  # work on body as single object
```
or may be something like:
```
if node.body.length
```
so this kind of unification does not look easier or cleaner to me.

Then there is:
```
# children=[...] vs. children=[obj]
# simply work on children array in both cases, no if necessary
```
however then you have a draw back when accessing the single object case:
```
obj = node.children[0]
# vs.
obj = node.expression # or node.body
```
So the decision is between preferring traversal or access. Which is done more often?
From the API point of view you could have a method obj(), which hides the array access.

I don't know if that matters, but the kind of solution should also affect optimizing javascript compilers.
body is polymorphic, so the code is probably a bit less optimizable.

**Comment by DmitrySoshnikov** [comment]
Hm.. good points and pros and cons overall.

> So the decision is between preferring traversal or access. Which is done more often?

Yeah, convenience of handling is definitely important, however, one more important thing here is semantics. It should be logically consistent: if the only thing a group can have is just a one "thing", it should not be an array.

Ideally traversal API should cover and abstract this away, so you don't have to manually deal with "if-else" checks for arrays, and not arrays. Though there probably might be cases when you manually have to traverse some nodes for some reason.

**Comment by hg42** [comment]
> if the only thing a group can have is just exactly one "thing", it should not be an array

I can accept that from one view, but why not have another?

You have "children" even if you have only one. Totally abstract you even have children if you have none (count is zero).

IMHO, that's a matter of view.
It's an abstraction. "One child" is only a special case of "children" just like a point is a circle with radius=0 which could also be a square with area=0. (btw. as we say in Germany "a position (viewpoint?) is a horizon (of experience) with radius=0" :-) hope that's correct in English).

Most tree systems (at least those I know) handle it like that, e.g. take the DOM where you have childNodes. It's simply more efficient, when you don't need an if or an indirection through object classes for each node.

If you need another (logical) view you can define aliases (access-methods) etc.
We are talking of different aspects, you can have different interfaces or sets of methods for certain aspects. A list can be used as queue or as array, so you have appropriate sets of methods, e.g. push and pop or putAt, getAt.
It's a bit like taking the sum of only one number, or even of no number -> edge cases of the same concept.

If you would want full OOP, you need total encapsulation of implementation details (which may be a good thing). You would have to go a huge step further and let the node objects store their children themselves, and let them decide how to iterate their children, so you would ask them for an iterator over their children. In C++ I would definitely do this. But I guess, several levels of indirection may have a huge performance hit in javascript.

A way in the middle would be the one usually chosen in inheritance based languages. You would have a base class "Node" with "children" and transparent algorithms like traversing would be defined on "Node"s. Concrete node objects would be derived from "Node". All access to members would go through methods anyway. So they each have their own view (interface) to their "children". The children would be seen as "expressions()" or "characters()" or a single "expression()" in case of a quantifier etc.

**Comment by DmitrySoshnikov** [comment]
@hg42, thanks for the detailed explanation, appreciated, all makes sense, and are valid points!

Re: AST nodes format.

We've been discussing previously with on having actual AST classes -- with the based `Node` class, getters, setters which abstract away a bunch of implementation details. The reason why it's yet a simple "plain-object" format is to be compatible with Mozilla Parser API, and different tools, like [AST Explorer](https://astexplorer.net/#/gist/4ea2b52f0e546af6fb14f9b2f5671c1c/39b55944da3e5782396ffa1fea3ba68d126cd394) which renders trees in JSON format, the same ast-traverse (which will probably going to remove anyways), and others. For this we could exposed `toJSON` method though. But in that `toJSON` will still have to return a property name "expression(s)". 

So the AST format is supposed to be JSON-encodable, and sharable (not only be processed in JS). We'll see though, I guess at some point we'll have to switch to actual class nodes though, but yet, I was trying to keep them as simple as possible.

Re: DOM childNodes example (and other abstractions, and perspectives) -- good examples, nothing to add it, I totally agree. Will have to think about restructuring (probably `Group` will receive `body` with 1 element).

As to the original question, I think practically it's access is made more often than the traversal. That's said, traversal should be abstracted away by the `traverse` module, and in practice one should not even do these "if-else" check for array/not-array. I'm trying to think of a case when one may need a manual traversal, or when it may happen often.

At access in a handler, one will have constantly to do:

```js
Group({node}) {
  const expression = node.expressions[0];
  ...
}
```

Which may cause questions - "why it's only `0`?", "if it's `0`, can it be other?", "if it can't be other, why we have to access it this way?" 

I still see the perspective of generic `childNodes` though :) So if we think access like this (and access will seems happen much more, than traversal), will be convenient, we can re-think, and switch to a generic format.

**Comment by hg42** [comment]
May be I am a bit too much into perfectionism.
Regexps are not that big. And you usually don't have many of them. So I guess ease of use comes first and performance last.
The traverse is written once.
Node objects are handled all the time.

Apart from that, I would suggest a way that is consistent.
* either the traversal runs outside the nodes,
all nodes have the same children collection
and can all be handled identically.
This is the classical imperative way and probably the most efficient, because there are no decisions or redirections.
* or the nodes are responsible itself,
then they can do whatever they want to store and manage their children,
and traverse() should ask a node object to apply the visitor function to all children (like `node.visitChildren(visit)`). E.g. a character range could invoke visit for the start and end character explicitly. This would also have impact on the remove() function because the object has to do it. Which may be good, because it is a specific operation, e.g. you cannot remove the end character from a range (->error).
This would be the object oriented way and the most flexible, because it all depends on the individual object.

If you keep it consistent, you get all the advantages. If you mix it, you get disadvantages from both.

From what you said, which are good points, I would conclude, the OOP way would be best:
* JSON sees the member names you want to see
* object handling is optimal and easier

disadvantages:
* performance of traversal is one level of indirection slower
* each node object needs to have a visitChildren function.
But this can be optimized by inheritance or by assignment of a common function.
E.g. you could assign a common `visitExpressions` function to the `visitChildren` member of all nodes using an expressions array.
* it's a bigger redesign, because certain concept would need a new solution.

For a limited set of object types like with regexps this may indeed be over-designed.
Sometimes an OOP-redesign gives new chances not seen before.
E.g. transformations turn from being defined by positions (node.expressions[1]) to using symbolic names (node.startChar).
But then you can no more define tree-algorithms like reordering in an abstract and generic way. This may be a huge disadvantage.

Btw. I think terms like "expressions" are more natural than "body". Any regexp definitions I know, always talks about expressions, so I think this is the common term. IMHO "body" is more about text. When parsed, the text body is divided and converted into specific objects like expressions for an Alternative or a start and end character for a Range.

**Comment by DmitrySoshnikov** [comment]
> The traverse is written once.
Node objects are handled all the time.

Yep, I came to the same conclusion, which makes me think nodes access should be optimized for convenience, and less the traversal (which is abstract away anyways by the `traverse`, or by `path.traverse` later).

>  E.g. a character range could invoke visit for the start and end character explicitly

BTW, this approach is used by the _generator_, which does [its own traversal](https://github.com/DmitrySoshnikov/regexp-tree/blob/master/src/generator/index.js#L20), calling `gen` function for needed sub-parts.

Also, following [Mozilla Parser API](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Parser_API) (which I aimed to target initially), this also semantically defines single `argument` e.g. for `UnaryExpression`, since the only thing an unary expression may have is just one arguments (like `-1`).

> Btw. I think terms like "expressions" are more natural than "body"

Now I think it's too, from the regular _expressions_. So probably just leave it then as `expression(s)` for now.

Both approaches you describe makes sense, though I agree it might a bigger redesign in general, and for now I think we should probably just keep it as is, and can re-iterate in the future if following Mozilla Parser API will be causing issues.

**Comment by DmitrySoshnikov** [comment]
Now when we have generic `getChild` which abstracts away `expression`, and `expressions` works pretty well (fixed in #47), I'm gonna close this issue for now. We can return to different ASTs format if the current one cause issues in the future.

**Comment by hg42** [comment]
`getChild` could get an optional property parameter like the other functions.
The strategy to detect if it's an array or a single child is a little different in different functions:
* `getChild`: looks if `node.expressions` exists, otherwise uses single child `node.expression`
* at some places index is used

`getChild` cannot use index, so may be the other functions should also look for `node.expressions`?

**Comment by hg42** [comment]
`setChild` and others cannot use `expressions` vs. `expression` for distinction, because of the `property` parameter. That is why it uses `index`.
Would all be simpler if no other property would be allowed.
